### ISSUE TITLE
Inclusion in criterion.

### ISSUE THREAD

**Issue by lemmih** [BurntSushi/critcmp#15]
Hi @BurntSushi,

I'd like for criterion to support this style of workflow but I'm not sure how to go about it. I see a few different options:
 1. Write a specification for the `baseline` data format and let external tools parse it on their own.
 2. Write a `criterion-baseline` library for loading and storing baselines.
 3. Merge `critcmp` into `criterion` or `cargo-criterion`.

I'm leaning towards option 2. What are your thoughts?

Also, is there a better name for a collection of benchmark results than "baseline"?

**Comment by BurntSushi** [comment]
I usually think of a collection of benchmark results as an "experiment" or an "experimental result." But maybe that's a little tied to my workflow.

To be honest, I don't know what the best path is here, and unfortunately, I just don't have the bandwidth to really dig into what the best way to do this is. :-( On its face, option (2) seems like a decent choice to me to be honest. As long as it doesn't kill `critcmp` compile times with a huge dependency tree, I'd be really happy to rely on a library to give me the data I want instead of trying to look under the covers. I think the main thing there is just making sure it exposes enough data for tools like `critcmp` to do their job.

**Comment by lemmih** [comment]
How do you feel about sharing the maintenance burden for `critcmp`? I'd like a future where `criterion` is more streamlined and approachable, with the `critcmp` workflow being official blessed and documented in the User's Guide. I don't have any changes in mind for `critcmp` but I'd like to help ensure that it is always actively maintained.

**Comment by BurntSushi** [comment]
@Lemmih Are you maintaining Criterion now? Sorry, I just want to make sure I know who I'm speaking to. :)

I am unsure about sharing maintenance at this point. I've done this a lot in the past. Sometimes it works, sometimes it doesn't. For a tiny tool like this, I think I'd almost prefer that the Criterion project build their own solution to the problem. If it fits my use cases, then I'd be happy to just outright deprecate critcmp. I much prefer that route over sharing maintenance if possible.

**Comment by lemmih** [comment]
Yes, I'm co-maintaining criterion.

Alright, I'll copy your code into criterion (love that you use `UNLICENSE`, btw). Bundling it with criterion (or cargo-criterion) does offer a more streamlined experience to end-users but I didn't want to step on your toes or steal your fame.

**Comment by BurntSushi** [comment]
Haha no it's great to ask! I always appreciate attribution, even when legally not required. :-)

But yes, in general, I am maintaining so many things that I'm usually pretty happy when someone comes along and provides something better. At least a few Rust crates have gone the way of the dodo because of that (`docopt` and `chan`, at least).

**Comment by bluenote10** [comment]
@lemmih I'm wondering what is the status now on integrating critcmp into criterion? I came across [your blog post](https://www.tweag.io/blog/2022-03-03-criterion-rs/) (great work!) and the improved results reporting was exactly what I was always missing in criterion. Unfortunately the "tabulating results" link in the blog post seems to be dead and I haven't found any such functionality in the latest version of criterion?

**Comment by lemmih** [comment]
Yeah, it was removed from criterion with the intention to move it to cargo-criterion. Contributing to cargo-criterion is difficult, though, so I haven't done the work yet.
